FROM debian:stable-slim

RUN apt-get update && apt-get install -y watchman

ADD --chmod=755 https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-arm64 /bin/tailwindcss
