services:
  db:
    image: postgres:17-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=virusscan
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      interval: 2s
      retries: 10
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    command: uv run python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - .:/app
      - clamav_socket:/clamav
      - files_scan:/files_scan
    depends_on:
      db:
        condition: service_healthy
        restart: true
  #      clamav:
  #        condition: service_healthy
  #        restart: true

  clamav:
    image: clamav/clamav:stable
    platform: linux/amd64
    volumes:
      - clamav_data:/var/lib/clamav
      - clamav_socket:/tmp
      - files_scan:/files_scan:ro
    healthcheck:
      test: /bin/sh -c '[ -e /tmp/clamd.sock ]'
      interval: 3s
      retries: 10

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: bash -c 'exec 6<>/dev/tcp/redis/6379'
      interval: 2s
      retries: 10

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uv run celery -A virusscan worker -l INFO --pool=solo
    volumes:
      - .:/app
      - clamav_socket:/clamav
      - files_scan:/files_scan
    environment:
      PYTHONUNBUFFERED: '1'
      PYTHONDONTWRITEBYTECODE: '1'
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      web:
        condition: service_started


volumes:
  clamav_data:
  clamav_socket:
  postgres_data:
  files_scan:
  redis_data:
