# syntax=docker/dockerfile:1.7-labs
FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y curl

RUN curl -o- https://deb.nodesource.com/setup_22.x \
    | bash && apt-get install -y nodejs watchman libpq5 && \
    node -v && \
    npm -v

# Install the project into `/app`
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Use a venv outside of the main folder
ENV UV_PROJECT_ENVIRONMENT=/usr/local/venv/

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

COPY uv.lock pyproject.toml ./
RUN uv sync --frozen

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

COPY --exclude=.venv . /app/